name: abdelmoneam_create_an_animation_scroll
description: "Abdelmoneam Flutter Animation Learning"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.8.0
  go_router: ^14.6.0
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/ibm body/
    - assets/fonts/ox title/
    - assets/images/
  fonts:
    - family: IbmBody
      fonts:
        - asset: assets/fonts/ibm body/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm body/IBMPlexSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/ibm body/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm body/IBMPlexSansArabic-SemiBold.ttf
          weight: 600

    - family: Ox title
      fonts:
        - asset: assets/fonts/ox title/Oxanium-Medium.ttf
          weight: 500
        - asset: assets/fonts/ox title/Oxanium-Regular.ttf
          weight: 400
        - asset: assets/fonts/ox title/Oxanium-SemiBold.ttf
          weight: 600
